Repository YeonJeans/Saera-Flutter, pull requests merged in 2023-03, with the labels that each got.

#48 [Fix] - Fix android record error
  android/.gitignore
  android/app/build.gradle
  assets/icons/close_toast.svg
  assets/icons/flower.svg
  ios/Podfile.lock
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/style/color.dart
  lib/style/font.dart
  pubspec.yaml
Labels: feature, design, fix

#49 [Design] - Redesign Home Screen
  assets/icons/expand_right.svg
  assets/icons/today_statement.svg
  assets/icons/today_word.svg
  assets/images/home_item_bg.png
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/home/presentation/home_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
  lib/style/font.dart
  pubspec.yaml
Labels: feature, design

#56 [Feature] - Add token issuance
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/login/data/cache_manager.dart
  lib/login/data/refresh_token.dart
  lib/login/presentation/login_screen.dart
Labels: feature, chore

#57 [Design] - Redesign Learn Screen
  assets/icons/company.svg
  assets/icons/conservation.svg
  assets/icons/custom_statement.svg
  assets/icons/etc.svg
  assets/icons/feeling.svg
  assets/icons/honorific.svg
  assets/icons/negative.svg
  assets/icons/order.svg
  assets/icons/public.svg
  assets/icons/question.svg
  assets/icons/shopping.svg
  assets/icons/statement_button_1.svg
  assets/icons/statement_button_1_1.svg
  assets/icons/statement_button_2.svg
  assets/icons/statement_button_2_1.svg
  assets/icons/word_button_1.svg
  assets/icons/word_button_2.svg
  assets/icons/word_main_next.svg
  lib/home/presentation/home_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_done_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_loading_screen.dart
  lib/learn/presentation/accent_main_screen.dart
  lib/learn/presentation/learn_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/style/color.dart
  lib/style/font.dart
Labels: feature, design

#58 [Fix] Fix error
  lib/home/presentation/home_screen.dart
  lib/style/font.dart
Labels: fix

#62 [Feature] - Add Tag Search
  assets/icons/click_check.svg
  assets/icons/greeting.svg
  assets/images/home_image.svg
  lib/home/presentation/home_screen.dart
  lib/learn/presentation/accent_main_screen.dart
  lib/learn/presentation/learn_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/style/color.dart
  lib/style/font.dart
Labels: feature, design, fix

#65 [Design] - Redesign Accent Main Screen
  lib/learn/presentation/accent_main_screen.dart
Labels: design

#66 [Design] - Design Today Learn List Screen
  lib/style/font.dart
  lib/today_learn_statement_list.dart
  lib/today_learn_word_list.dart
Labels: design

#72 [Design] - Design Custom Statement Screen
  assets/icons/box_open.svg
  assets/icons/plus.svg
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/presentation/accent_main_screen.dart
  lib/style/font.dart
Labels: feature, design

#76 [Fix] Fix the method to calculate exp level
  lib/login/presentation/login_screen.dart
  lib/mypage/presentation/mypage_screen.dart
  lib/mypage/presentation/widgets/mypage_userInfo.dart
Labels: chore, fix

#78 [Chore] Persistent TabBar
  lib/home/presentation/home_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/presentation/accent_main_screen.dart
  lib/learn/presentation/learn_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
  lib/learn/presentation/widgets/learn_category_icon_tile.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/tabbar.dart
  lib/today_learn_statement_list.dart
  lib/today_learn_word_list.dart
Labels: feature, chore

#74 [Design] - Design Word Learn Complete Screen
  lib/today_learn_word_list.dart
Labels: design, chore

#82 [Feature/#80] Connect Server in Pronounce Main Screen
  lib/learn/presentation/pronunciation_main_screen.dart
Labels: feature

#83 [Feature] Connect Page
  lib/home/presentation/home_screen.dart
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
  lib/learn/pronounce_learn/pronounce_learn_screen.dart
  lib/learn/pronounce_learn/widgets/word_tag.dart
  lib/mypage/presentation/widgets/mypage_userInfo.dart
  lib/style/font.dart
  lib/tabbar.dart
Labels: feature, design, setting

#84 [Feat] Add line on graph
  lib/learn/accent_learn/data/line_controller.dart
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/accent_learn/presentation/widgets/accent_line_chart.dart
  lib/learn/accent_learn/presentation/widgets/audio_bar.dart
  lib/learn/pronounce_learn/pronounce_learn_screen.dart
  lib/main.dart
Labels: feature, design

#87 [Feature] - Connect Server
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
Labels: feature

#86 [Fix] - Fix error in line graph
  lib/learn/accent_learn/data/line_controller.dart
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/accent_learn/presentation/widgets/accent_line_chart.dart
  lib/learn/accent_learn/presentation/widgets/audio_bar.dart
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/widgets/create_sentence_background.dart
  lib/learn/custom_learn/create_sentence/presentation/widgets/subtitle_section.dart
  lib/style/color.dart
  lib/style/font.dart
  lib/tabbar.dart
Labels: fix

#92 [Fix] - Fix Top5 Sentence and ListView Size
  lib/home/presentation/home_screen.dart
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
Labels: feature, fix

#97 [Feature] - Add Recommend Container on Semantic Search Statement
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/learn/search_learn/presentation/widgets/response_statement.dart
  lib/style/font.dart
Labels: feature

#99 [Feature] - Connect Custom Learn Page
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/home/presentation/home_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/accent_learn/presentation/today_learn_statement_list.dart
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_done_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_loading_screen.dart
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/pronounce_learn/pronounce_learn_screen.dart
  lib/learn/pronounce_learn/today_learn_word_list.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/style/font.dart
Labels: feature, design, fix

#101 [Feature] - Page Move
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_done_screen.dart
Labels: feature, chore

#103 [Feat] Connect custom page & Modify graph
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/home/presentation/home_screen.dart
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/widgets/accent_line_chart.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_done_screen.dart
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
Labels: feature

#107 [Feat/Chore] - Create null point in line graph / Change detail design
  assets/icons/home_filled.svg
  assets/icons/home_outlined.svg
  assets/icons/learn_filled.svg
  assets/icons/learn_outlined.svg
  assets/icons/star_filled.svg
  assets/icons/star_outlined.svg
  assets/icons/user_filled.svg
  assets/icons/user_outlined.svg
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/home/presentation/home_screen.dart
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/accent_learn/presentation/widgets/accent_line_chart.dart
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_done_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_loading_screen.dart
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/presentation/accent_main_screen.dart
  lib/learn/presentation/learn_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
  lib/learn/pronounce_learn/pronounce_learn_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/login/presentation/login_screen.dart
  lib/main.dart
  lib/mypage/presentation/mypage_screen.dart
  lib/style/font.dart
  lib/tabbar.dart
Labels: feature, design, chore

#110 [Fix] - Fix Error
  android/app/src/main/res/drawable-hdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-mdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xhdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/icons/saera_app_icon.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-1024x1024@1x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-20x20@1x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-20x20@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-20x20@3x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-29x29@1x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-29x29@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-29x29@3x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-40x40@1x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-40x40@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-40x40@3x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-50x50@1x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-50x50@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-57x57@1x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-57x57@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-60x60@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-60x60@3x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-72x72@1x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-72x72@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-76x76@1x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-76x76@2x.png
  ios/Runner/Assets.xcassets/true.appiconset/true-83.5x83.5@2x.png
  lib/home/presentation/home_screen.dart
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  pubspec.yaml
Labels: design, chore, fix

#112 [Fix] - Add argument
  lib/home/presentation/home_screen.dart
Labels: fix

#116 [Design] - Modify Design
  assets/images/home_speech_bubble.png
  lib/home/presentation/home_screen.dart
  lib/learn/accent_learn/presentation/today_learn_statement_list.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_done_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/custom_statement_loading_screen.dart
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/presentation/accent_main_screen.dart
  lib/learn/presentation/learn_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
  lib/learn/pronounce_learn/today_learn_word_list.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/style/font.dart
Labels: feature, design, chore

#117 [Feature] - Add Filter in Bookmark Screen
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/presentation/pronunciation_main_screen.dart
Labels: feature, chore

#122 [Chore] Modify Detail
  assets/images/saera_splash.svg
  assets/images/saera_title.svg
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
  lib/learn/pronounce_learn/pronounce_learn_screen.dart
  lib/learn/pronounce_learn/widgets/word_tag.dart
  lib/login/presentation/login_screen.dart
  lib/main.dart
  lib/style/font.dart
  lib/tabbar.dart
Labels: design, chore

#128 [Chore] - Modify Detail
  lib/home/presentation/home_screen.dart
Labels: chore

#131 [Fix] Fix error in android record in other device
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
Labels: fix
