Repository YeonJeans/Saera-Flutter, pull requests merged in 2023-05, with the labels that each got.

#134 [Feature] - Connect Continuous Learn Date API
  lib/home/presentation/home_screen.dart
Labels: feature, refactor

#136 [Fix] - Modify ListView Error & Chip Error
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
Labels: fix

#142 [Feat] - Add Apple login
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  assets/images/apple_logo.png
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/login/data/user_info_controller.dart
  lib/login/presentation/login_screen.dart
  lib/main.dart
  lib/mypage/mypage_edit_screen.dart
  lib/mypage/presentation/mypage_screen.dart
  lib/mypage/presentation/widgets/liquid_custom_progress.dart
  lib/mypage/presentation/widgets/mypage_userInfo.dart
  lib/tabbar.dart
  pubspec.yaml
Labels: feature

#139 [Feat] - Add edit user profile feature
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  assets/images/apple_logo.png
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/login/data/user_info_controller.dart
  lib/mypage/mypage_edit_screen.dart
  lib/mypage/presentation/mypage_screen.dart
  lib/mypage/presentation/widgets/liquid_custom_progress.dart
  lib/mypage/presentation/widgets/mypage_userInfo.dart
  pubspec.yaml
Labels: feature

#147 [Feat] - Show standard accent graph with user's accent graph
  lib/home/presentation/home_screen.dart
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/accent_learn/presentation/widgets/accent_line_chart.dart
  pubspec.yaml
Labels: feature, design
