Repository YeonJeans/Saera-Flutter, pull requests merged in 2023-06, with the labels that each got.

#148 [Feature/#144] Show Dialog in Pronunciation Learn Screen
  lib/learn/pronounce_learn/pronounce_learn_screen.dart
Labels: feature

#149 Doeun feat/#141
  assets/fword_list.txt
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/accent_learn/presentation/accent_todaylearn_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/widgets/check_badword.dart
  lib/learn/pronounce_learn/pronounce_learn_screen.dart
  lib/style/font.dart
  pubspec.yaml
Labels: feature, design, chore

#151 [Fix] Fix conflict error in show dialog
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
Labels: fix

#150 [Fix/#146] - Fix Custom Statement List in Bookmark Page
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
  lib/learn/custom_learn/learn_sentence/presentation/learn_statement_screen.dart
  lib/learn/pronounce_learn/pronounce_learn_screen.dart
  lib/style/font.dart
Labels: feature, fix

#152 [Chore] Modify detail design
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
Labels: chore
