Repository YeonJeans/Saera-Flutter, pull requests merged in 2023-02, with the labels that each got.

#22 [Design] - Design MyPage UI
  assets/icons/mypage_profile.svg
  assets/icons/mypage_profile_bg.svg
  assets/icons/user_profile.png
  assets/images/mypage_flower.png
  lib/mypage/presentation/mypage_screen.dart
  lib/mypage/presentation/widgets/mypage_background_image.dart
  lib/mypage/presentation/widgets/mypage_userInfo.dart
  lib/style/font.dart
Labels: design

#23 [Feature] - Connect SearchLearnScreen Search API
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/learn/search_learn/presentation/widgets/response_statement.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#26 [Feature/#24] Connect SearchLearnPage and AccentLearnPage
  lib/learn/search_learn/presentation/search_learn_screen.dart
Labels: feature

#28 [Fix] Modify Category Height Overflowed Error
  lib/learn/presentation/learn_screen.dart
Labels: fix

#32 [Fix] - Fix Error
  ios/Podfile
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/learn/presentation/widgets/learn_category_icon_tile.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/learn/search_learn/presentation/widgets/response_statement.dart
Labels: fix

#34 [Feature] - Connect BookmarkScreen API
  lib/home/bookmark_home/presentation/bookmark_home_screen.dart
Labels: feature

#36 [Design] - Design Beginning Screen
  .gitignore
  assets/icons/google_logo.png
  ios/Podfile.lock
  lib/login/presentation/login_screen.dart
  lib/main.dart
  lib/style/font.dart
  lib/tabbar.dart
  pubspec.yaml
Labels: design

#38 [Feature] - iOS GoogleLogin
  ios/Runner/Info.plist
  lib/learn/accent_learn/presentation/widgets/accent_line_chart.dart
  lib/login/data/login_platform.dart
  lib/login/presentation/login_screen.dart
Labels: feature

#39 [Feature] - Add Tag Search And Filter
  assets/icons/filter_down.svg
  assets/icons/filter_up.svg
  lib/learn/presentation/widgets/learn_category_icon_tile.dart
  lib/learn/presentation/widgets/learn_category_list_tile.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/learn/search_learn/presentation/widgets/choice_chip.dart
  lib/style/color.dart
Labels: feature

#42 [Fix] - Fix android google login error
  lib/login/presentation/login_screen.dart
  lib/mypage/presentation/mypage_screen.dart
Labels: fix

#43 [Design] - Create Sentence Screen
  assets/icons/correct.svg
  assets/icons/delete.svg
  assets/icons/incorrect.svg
  lib/learn/custom_learn/create_sentence/presentation/create_sentence_screen.dart
  lib/learn/custom_learn/create_sentence/presentation/widgets/create_sentence_background.dart
  lib/learn/custom_learn/create_sentence/presentation/widgets/subtitle_section.dart
  lib/style/color.dart
  lib/style/font.dart
Labels: feature, design

#44 [Design] - Design Loading UI
  assets/icons/check_round_fill.svg
  assets/icons/three_dots.svg
  lib/custom_statement_done_screen.dart
  lib/custom_statement_loading_screen.dart
  lib/learn/search_learn/presentation/search_learn_screen.dart
  lib/learn/search_learn/presentation/widgets/choice_chip.dart
  lib/style/color.dart
  lib/style/font.dart
  pubspec.yaml
Labels: feature, fix

#47 [Feature] - Add token management and automatic login
  ios/Runner/Info.plist
  lib/learn/accent_learn/presentation/accent_learn_screen.dart
  lib/login/data/authentication_manager.dart
  lib/login/data/cache_manager.dart
  lib/login/presentation/login_screen.dart
  lib/login/presentation/widget/onboard_widget.dart
  lib/main.dart
  pubspec.yaml
Labels: feature, chore
